name: khadok_application_8
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  url_launcher: ^6.0.18
  webview_flutter: ^3.0.0
  # google_maps_flutter: ^2.1.1
  # fluttertoast: ^8.0.8
  # cached_network_image: ^3.2.0
  
  




  

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/ic_launcher.png" 


   

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/download.png
    - assets/json/jomor_image.json
    - assets/json/kari_image.json
    - assets/json/green_image.json
    - assets/json/nobabi.json
    - assets/json/noumi.json
    - assets/json/hungry.json
    - assets/json/silver.json
    - assets/json/dhaka.json
    - assets/json/hello.json
    - assets/json/frego.json
    - assets/json/food.json
    - assets/json/raduni_link.json
    - assets/json/raduni_link.json
    - assets/image/bangladeshi-food.png
    - assets/image/jomor_hotel.png
    - assets/image/kari_hotel.png
    - assets/image/radhoni_hotel.png
    - assets/image/green_chilli.png
    - assets/image/cafe_nobabi.png
    - assets/image/hotel_noumi.png
    - assets/image/hungry.png
    - assets/image/silver_fork.png
    - assets/image/frego.png
    - assets/image/dhaka_food.png
    - assets/image/hello_ restaurant.png
    - assets/image/food_zone.png
    - assets/image/2018-07-02 jomor.png
    - assets/image/2019-11-06 jomor.png
    - assets/image/2020-02-19 jomor.png
    - assets/image/IMG_20200613_221046 kari.png
    - assets/image/2020-03-03 kari.png
    - assets/image/2018-08-12 kari.png
    - assets/image/2018-01-20 kari.png
    - assets/image/2017-12-25 kari.png
    - assets/image/green.png
    - assets/image/green2.png
    - assets/image/green3.png
    - assets/image/green 4.png
    - assets/image/green 5.png
    - assets/image/noumi.png
    - assets/image/noumi1.png
    - assets/image/noumi2.png
    - assets/image/noumi4.png
    - assets/image/noumi.5.png
    - assets/image/nobabi.png
    - assets/image/nobabi1.png
    - assets/image/nobabi2.png
    - assets/image/nobabi3.png
    - assets/image/nobabi4.png
    - assets/image/nobabi5.png
    - assets/image/hungry.png
    - assets/image/hungry1.png
    - assets/image/hungry2.png
    - assets/image/hungry3.png
    - assets/image/hungry4.png
    - assets/image/hungry5.png
    - assets/image/silver (1).png
    - assets/image/silver (2).png
    - assets/image/silver (3).png
    - assets/image/silver (4).png
    - assets/image/silver (5).png
    - assets/image/silver (6).png
    - assets/image/dhaka (1).png
    - assets/image/dhaka (2).png
    - assets/image/dhaka (3).png
    - assets/image/dhaka (4).png
    - assets/image/dhaka (5).png
    - assets/image/hello.png
    - assets/image/hello1.png
    - assets/image/frego (3).png
    - assets/image/frego (4).png
    - assets/image/frego (5).png
    - assets/image/frego (6).png
    - assets/image/frego (7).png
    - assets/image/frego (8).png
    - assets/image/food.png
    - assets/image/food1.png
    - assets/image/food2.png
    - assets/image/food3.png
    - assets/image/food4.png
    - assets/image/raduni.png
    - assets/image/raduni1.png
    - assets/image/raduni2.png

    

    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
